CREATE TABLE products
(
ID SERIAL NOT NULL,
PRODUCT_NAME VARCHAR(255) NOT NULL,
PRODUCT_DESC TEXT NOT NULL,
SELLER VARCHAR(255) NOT NULL,   /*Mudar para hiperligação*/
QUANTITY REAL NOT NULL,
PRICE REAL NOT NULL
);